# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ALM_GMD <- function(y, Z, Zc, Zc_proj, beta, lambda, pf, dfmax, pfmax, A, b, group_index, inner_maxiter, outer_maxiter, inner_eps, outer_eps, mu_ratio, u_ini, tol) {
    .Call(`_compReg_ALM_GMD`, y, Z, Zc, Zc_proj, beta, lambda, pf, dfmax, pfmax, A, b, group_index, inner_maxiter, outer_maxiter, inner_eps, outer_eps, mu_ratio, u_ini, tol)
}

ALM_BG <- function(y, Z, Zc, Zc_proj, beta, lambda, pf, b, A, dfmax, pfmax, inner_maxiter, outer_maxiter, inner_eps, outer_eps, mu_ratio, u_ini, tol) {
    .Call(`_compReg_ALM_BG`, y, Z, Zc, Zc_proj, beta, lambda, pf, b, A, dfmax, pfmax, inner_maxiter, outer_maxiter, inner_eps, outer_eps, mu_ratio, u_ini, tol)
}

ALM_B <- function(y, Z, Zc, Zc_proj, beta, lambda, pf, dfmax, pfmax, inner_maxiter, outer_maxiter, inner_eps, outer_eps, mu_ratio, u_ini, tol) {
    .Call(`_compReg_ALM_B`, y, Z, Zc, Zc_proj, beta, lambda, pf, dfmax, pfmax, inner_maxiter, outer_maxiter, inner_eps, outer_eps, mu_ratio, u_ini, tol)
}

